import { useState } from 'react';
import { View, Text, TextInput, Button, StyleSheet, ScrollView, Alert } from 'react-native';
import { useAppStore } from '../lib/store';

export default function ExplainScreen() {
  const { labParameters, addLabParameter, symptoms } = useAppStore();
  const [name, setName] = useState('');
  const [value, setValue] = useState('');
  const [unit, setUnit] = useState('');

  const handleAddLab = () => {
    if (!name.trim() || !value.trim() || !unit.trim()) {
      Alert.alert('Missing fields', 'Please fill all lab fields');
      return;
    }
    addLabParameter(name.trim(), parseFloat(value), unit.trim());
    setName('');
    setValue('');
    setUnit('');
  };

  const handleGetExplanation = () => {
    if (labParameters.length === 0) {
      Alert.alert('No labs', 'Please add at least one lab parameter first.');
      return;
    }
    // Mock AI explanation based on labs and symptoms
    const labList = labParameters.map(l => `${l.name}: ${l.value} ${l.unit}`).join(', ');
    const symptomList = symptoms.map(s => s.text).join(', ') || 'no symptoms provided';

    const explanation = `[Mock AI Explanation]\n\nBased on your symptoms: ${symptomList}\nAnd your lab results: ${labList}\n\nThis is an educational interpretation. In the real app, this would be generated by an LLM with safety checks, providing plain-language explanations, confidence scores, and next-step guidance.`;
    Alert.alert('AI Explanation', explanation);
  };

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>Lab Entry & Explanation</Text>
      <Text style={styles.subtitle}>Enter lab parameters one by one</Text>

      <TextInput
        style={styles.input}
        placeholder="Parameter name (e.g., Hemoglobin)"
        value={name}
        onChangeText={setName}
      />
      <TextInput
        style={styles.input}
        placeholder="Value (e.g., 12.5)"
        value={value}
        onChangeText={setValue}
        keyboardType="numeric"
      />
      <TextInput
        style={styles.input}
        placeholder="Unit (e.g., g/dL)"
        value={unit}
        onChangeText={setUnit}
      />

      <Button title="Add Lab Parameter" onPress={handleAddLab} />

      <View style={styles.list}>
        {labParameters.map((l) => (
          <View key={l.id} style={styles.item}>
            <Text>{l.name}: {l.value} {l.unit}</Text>
          </View>
        ))}
      </View>

      {labParameters.length > 0 && (
        <Button title="Get AI Explanation" onPress={handleGetExplanation} />
      )}

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Your Symptoms (for context)</Text>
        {symptoms.map((s) => (
          <Text key={s.id}>• {s.text}</Text>
        ))}
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: '#fff',
    flexGrow: 1,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  list: {
    marginTop: 20,
    marginBottom: 20,
  },
  item: {
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  section: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#ccc',
  },
  sectionTitle: {
    fontWeight: 'bold',
    marginBottom: 8,
  },
});
